name: Enable auto-merge
on:
  pull_request:
    types:
      - labeled
  workflow_call:
    inputs:
      pullRequestId:
        description: node ID of the PR to update
        required: true
        type: string
      mergeMethod:
        description: one of https://docs.github.com/en/graphql/reference/enums#pullrequestmergemethod
        default: SQUASH
        type: string
      token:
        required: false
        type: string
    secrets:
      token:
        required: false
jobs:
  enable:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@a60f9ba870efadf6bf59e01296e9061052a31b39 # tag=v2.2.23
        id: enablePullRequestAutoMerge
        with:
          query: |
            mutation(
              $pullrequestid: ID!,
              $mergemethod: PullRequestMergeMethod!
            ) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullrequestid,
                  mergeMethod: $mergemethod
                }) {
                clientMutationId
                pullRequest {
                  id
                  state
                  autoMergeRequest {
                    enabledAt
                    enabledBy {
                      login
                    }
                  }
                }
              }
            }

          pullrequestid: ${{ inputs.pullRequestId || github.event.pull_request.node_id }}
          mergemethod: ${{ inputs.mergeMethod || 'SQUASH' }}
        env:
          GITHUB_TOKEN: ${{ secrets.token || inputs.token || github.token }}
      - run: "echo '${{ steps.enablePullRequestAutoMerge.outputs.data }}'"