name: Enable auto-merge
on:
  workflow_call:
    inputs:
      pullRequestId:
        description: node ID of the PR to update
        required: true
        type: string
      mergeMethod:
        description: one of https://docs.github.com/en/graphql/reference/enums#pullrequestmergemethod
        default: SQUASH
        type: string
      use_app_token:
        type: boolean
        default: false
    secrets:
      token:
        required: false
      app_id:
        required: false
      private_key:
        required: false
jobs:
  enable:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        if: ${{ inputs.use_app_token }}
        id: token
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}

      - uses: octokit/graphql-action@75105ddc89d71a35eca847e7a011028198ca6ec5 # v2.2.24
        id: enablePullRequestAutoMerge
        with:
          query: |
            mutation(
              $pullrequestid: ID!,
              $mergemethod: PullRequestMergeMethod!
            ) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullrequestid,
                  mergeMethod: $mergemethod
                }) {
                clientMutationId
                pullRequest {
                  id
                  state
                  autoMergeRequest {
                    enabledAt
                    enabledBy {
                      login
                    }
                  }
                }
              }
            }

          pullrequestid: ${{ inputs.pullRequestId || github.event.pull_request.node_id }}
          mergemethod: ${{ inputs.mergeMethod || 'SQUASH' }}
        env:
          GITHUB_TOKEN: ${{ secrets.token || steps.token.outputs.token || github.token }}
      - run: "echo '${{ steps.enablePullRequestAutoMerge.outputs.data }}'"