name: Automatically merge the default branch into PRs with auto-merge enabled
on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
  workflow_call:
    inputs:
      pullRequestId:
        description: node ID of the PR to update
        required: true
        type: string
      mergeMethod:
        description: one of https://docs.github.com/en/graphql/reference/enums#pullrequestmergemethod
        default: SQUASH
        type: string
      token:
        required: false
        type: string
    secrets:
      token:
        required: false
jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@a60f9ba870efadf6bf59e01296e9061052a31b39 # tag=v2.2.23
        if: secrets.token != ""
        with:
          query: |
            mutation(
              $pullrequestid: ID!,
              $mergemethod: PullRequestMergeMethod!
            ) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullrequestid,
                  mergeMethod: $mergemethod
                }) {
                clientMutationId
                pullRequest {
                  id
                  state
                  autoMergeRequest {
                    enabledAt
                    enabledBy {
                      login
                    }
                  }
                }
              }
            }

          pullrequestid: ${{ inputs.pullRequestId }}
          mergemethod: ${{ inputs.mergeMethod }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

      - uses: octokit/graphql-action@a60f9ba870efadf6bf59e01296e9061052a31b39 # tag=v2.2.23
        if: inputs.token != ""
        with:
          query: |
            mutation(
              $pullrequestid: ID!,
              $mergemethod: PullRequestMergeMethod!
            ) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullrequestid,
                  mergeMethod: $mergemethod
                }) {
                clientMutationId
                pullRequest {
                  id
                  state
                  autoMergeRequest {
                    enabledAt
                    enabledBy {
                      login
                    }
                  }
                }
              }
            }

          pullrequestid: ${{ inputs.pullRequestId }}
          mergemethod: ${{ inputs.mergeMethod }}
        env:
          GITHUB_TOKEN: ${{ inputs.token }}

      - uses: octokit/graphql-action@a60f9ba870efadf6bf59e01296e9061052a31b39 # tag=v2.2.23
        if: inputs.token == "" && secrets.token == ""
        with:
          query: |
            mutation(
              $pullrequestid: ID!,
              $mergemethod: PullRequestMergeMethod!
            ) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullrequestid,
                  mergeMethod: $mergemethod
                }) {
                clientMutationId
                pullRequest {
                  id
                  state
                  autoMergeRequest {
                    enabledAt
                    enabledBy {
                      login
                    }
                  }
                }
              }
            }

          pullrequestid: ${{ inputs.pullRequestId }}
          mergemethod: ${{ inputs.mergeMethod }}
        env:
          GITHUB_TOKEN: ${{ github.token }}