name: debug
on:
  push:
  workflow_call:
  workflow_dispatch: 
  schedule:
    - cron:  '0 0 * * *'
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"