name: Renovate
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    secrets:
      RENOVATE_APP_PEM:
        required: true
      RENOVATE_APP_ID:
        required: true
    inputs:
      renovate_app_slug:
        required: true
        type: string
      configuration_file:
        required: false
        type: string
        default: renovate.js
  schedule:
    - cron: '0 */4 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        id: token
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Renovate
        uses: renovatebot/github-action@78179592fbdafad8276d547ce30a1e7b63cf395e # v34.145.1
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: >-
            ${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }}[bot]
          RENOVATE_GIT_AUTHOR: >-
            ${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }} <${{ secrets.RENOVATE_APP_ID }}+${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }}[bot]@users.noreply.github.com>
          GITHUB_COM_TOKEN: '${{ steps.token.outputs.token }}'
          RENOVATE_GITHUB_COM_TOKEN: '${{ steps.token.outputs.token }}'
          RENOVATE_REQUIRE_CONFIG: 'false'
          RENOVATE_ONBOARDING: 'false'
        with:
          configurationFile: ${{ inputs.configuration_file }}
          token: 'x-access-token:${{ steps.token.outputs.token }}'
