name: Renovate
on:
  workflow_call:
    secrets:
      RENOVATE_APP_PEM:
        required: true
      RENOVATE_APP_ID:
        required: true
    inputs:
      dry_run_branch:
        description: |
          Validate the config on this branch, merged on top of the config from the default branch.
          Requires that config be in the same location on each branch.
          Requires that config be stored in a default configuration location.
          https://docs.renovatebot.com/configuration-options/#configuration-options
        required: false
        type: string
      onboarding:
        description: Require a Configuration PR to setup renovate.json.
        required: false
        type: string
        default: "false"
      renovate_app_slug:
        required: true
        type: string
      configuration_file:
        required: false
        type: string
        default: renovate.js
jobs:
  renovate:
    name: ${{ inputs.dry_run_branch == '' && 'Update' || 'Validate' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: token
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Detect optional self-hosted configuration
        id: config
        env:
          config_file: ${{ inputs.configuration_file }}
        run: |
          if [ -f "$config_file" ]; then
            echo "Using Renovate self-hosted config in $config_file."
            echo "https://docs.renovatebot.com/self-hosted-configuration/"
            echo "file=$config_file" >> $GITHUB_OUTPUT
          else
            echo "No Renovate self-hosted config found in $config_file". Using empty config.
            echo "https://docs.renovatebot.com/self-hosted-configuration/"
            echo "module.exports = {};" > renovate.js
            echo "file=renovate.js" >> $GITHUB_OUTPUT
          fi

      - name: Renovate
        if: inputs.dry_run_branch == ''
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        env:
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: >-
            ${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }}[bot]
          RENOVATE_GIT_AUTHOR: >-
            ${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }} <${{ secrets.RENOVATE_APP_ID }}+${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }}[bot]@users.noreply.github.com>
          GITHUB_COM_TOKEN: "${{ steps.token.outputs.token }}"
          RENOVATE_GITHUB_COM_TOKEN: "${{ steps.token.outputs.token }}"
          RENOVATE_REQUIRE_CONFIG: >-
            ${{ inputs.onboarding == 'false' && 'optional' || 'required' }}
          RENOVATE_ONBOARDING: >-
            ${{ inputs.onboarding || 'false' }}
          RENOVATE_ONBOARDING_CONFIG_FILE_NAME: renovate.json
          RENOVATE_ONBOARDING_CONFIG: |
            {
              "$schema": "https://docs.renovatebot.com/renovate-schema.json",
              "extends": ["github>urcomputeringpal/.github"],
            }
        with:
          # renovate: datasource=github-releases depName=renovatebot/renovate
          renovate-version: 36.107.1
          configurationFile: "${{ steps.config.outputs.file }}"
          token: "x-access-token:${{ steps.token.outputs.token }}"

      - name: Inspect configuration on default branch
        if: inputs.dry_run_branch != ''
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          path: default_branch
          ref: ${{ github.event.repository.default_branch }}

      - name: Detect default branch repository configuration
        if: inputs.dry_run_branch != ''
        id: default_branch_repo_config
        run: |
          if [ -f default_branch/renovate.json ]; then
            echo "Renovate config detected on default branch."
            echo "file=renovate.json" >> $GITHUB_OUTPUT
          else
            echo "No renovate config detected on default branch."
            echo "file=" >> $GITHUB_OUTPUT
          fi
          rm -rf default_branch

      - name: Dry run
        if: inputs.dry_run_branch != '' && steps.default_branch_repo_config.outputs.file != ''
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        env:
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: >-
            ${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }}[bot]
          RENOVATE_GIT_AUTHOR: >-
            ${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }} <${{ secrets.RENOVATE_APP_ID }}+${{ inputs.renovate_app_slug == '' && 'ur-renovate' || inputs.renovate_app_slug }}[bot]@users.noreply.github.com>
          GITHUB_COM_TOKEN: "${{ steps.token.outputs.token }}"
          RENOVATE_GITHUB_COM_TOKEN: "${{ steps.token.outputs.token }}"
          RENOVATE_REQUIRE_CONFIG: "optional"
          RENOVATE_ONBOARDING: "false"
          LOG_FORMAT: "json"
          RENOVATE_DRY_RUN: "full"
          RENOVATE_BASE_BRANCHES: ${{ inputs.dry_run_branch == '' && github.ref_name || inputs.dry_run_branch }}
          RENOVATE_USE_BASE_BRANCH_CONFIG: merge
        with:
          # renovate: datasource=github-releases depName=renovatebot/renovate
          renovate-version: 36.107.1
          configurationFile: "${{ steps.config.outputs.file }}"
          token: "x-access-token:${{ steps.token.outputs.token }}"
